# ______ _                      ______
# | ___ \ |                     | ___ \
# | |_/ / | __ _ _   _  ___ _ __| |_/ / __ _ _ __
# |  __/| |/ _` | | | |/ _ \ '__| ___ \/ _` | '_ \
# | |   | | (_| | |_| |  __/ |  | |_/ / (_| | | | |
# \_|   |_|\__,_|\__, |\___|_|  \____/ \__,_|_| |_|
#                 __/ |
#                |___/
# Config File
# Version: 2.0.0-Dev

#Set your language here
#English (eng),
#German (deu)
language: eng

#Specify here how you want to save the data
#Available: sqlite, mysql
datamanager: sqlite

#MySQL Connection
mysql-connection:
  host: 127.0.0.1
  username: root
  passwd: password
  dbname: playerban
  port: 3306

#Specify here your date format
#Available: dd.mm.yyyy, mm.dd.yyyy, yyyy.mm.dd
date-format: 'dd.mm.yyyy'

#Set here the message that appears when a banned player wants to enter the server
#Moderator: {moderator}
#Expiration date: {expiry}
#New line: {new_line}
kick-message: '&cYou are banned!{new_line}{new_line}&4Expiry: &f{expiry}'
