# ______ _                      ______
# | ___ \ |                     | ___ \
# | |_/ / | __ _ _   _  ___ _ __| |_/ / __ _ _ __
# |  __/| |/ _` | | | |/ _ \ '__| ___ \/ _` | '_ \
# | |   | | (_| | |_| |  __/ |  | |_/ / (_| | | | |
# \_|   |_|\__,_|\__, |\___|_|  \____/ \__,_|_| |_|
#                 __/ |
#                |___/
# Config File
# Version: 1.0.0

#MySQL Connection
host: 127.0.0.1
username: root
passwd: password
dbname: playerban
port: 3306
